### ISSUE TITLE
CLI image hangs on desktop install

### ISSUE THREAD

**Issue by sakittelsen** [radxa-build/rock-4se#3]
When using the Debian cli image and installing a desktop using tasksel, the process hangs during the "Prepairing to configure plymouth".
After a power-off and running "sudo dpkg --configure -a" fixes the install.

**Comment by sakittelsen** [comment]
I guess this could be a Debian issue, so closing it.

**Comment by sakittelsen** [comment]
This happens when installing any desktop using tasksel, so I don't think is a Debian issue.

**Comment by sakittelsen** [comment]
Update:
The reason it hangs on the tasksel install is that there is a "hidden" question during the setup. When using apt install task-xfce-desktop instead of tasksel, I can see why it stops the setup. Here is what it says:

Configuration file '/etc/plymouth/plymouthd.conf'
== File on system created by you or by script.
== File also in package provided by package maintainer.
What would you like to do about it?
The default is to use the currently-installed version.

That is what I select and it works.

**Comment by RadxaYuntian** [comment]
Custom DE on CLI image is [currently unsupported](https://forum.radxa.com/t/where-to-report-issues-on-radxa-distros/18687/3?u=radxayuntian).
