### ISSUE TITLE
Ubuntu XFCE never boots to the desktop

### ISSUE THREAD

**Issue by ghost** [radxa-build/rock-4se#6]
The image 'Rock-4se_ubuntu_focal_xfce_b38' never boots to the desktop. It hangs in the boot process.

**Comment by RadxaYuntian** [comment]
Ubuntu Desktop is currently [known broken](https://github.com/radxa-build/rock-3c#what-images-are-provided) and will require some investigation to get it working.

**Comment by webfinder42** [comment]
Debian Xfce is the recommend way to go right? if you want desktop..

**Comment by RadxaYuntian** [comment]
On ROCK 4 we support Debian KDE system.

I'll close this issue as the OP is deleted.
